apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: sample-app
        image: sriram323/sampleagrocd:latest
        ports:
        - containerPort: 8080
